services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - type: bind
        source: /mnt/f/Dev/eBaySalesTool/backend/src
        target: /app/src
      - type: bind
        source: /mnt/f/Dev/eBaySalesTool/backend/models
        target: /app/models
      - type: bind
        source: /mnt/f/Dev/eBaySalesTool/backend/package.json
        target: /app/package.json
      # Updated to use absolute paths for WSL compatibility
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://database:27017/ebay-sales-tool # Update MongoDB URI

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - REACT_APP_API_URL=http://localhost:5000

  database:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
