version: '3.8'
services:
  database:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: securepassword
    volumes:
      - ./test_mount:/docker-entrypoint-initdb.d:ro
    command: ["docker-entrypoint.sh"]
