services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules # Prevents overwriting node_modules
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://database:27017/ebay-sales-tool # Update MongoDB URI

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules # Prevents overwriting node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:5000

  database:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
