services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - type: bind
        source: /mnt/f/Dev/eBaySalesTool/backend/src
        target: /app/src
      - type: bind
        source: /mnt/f/Dev/eBaySalesTool/backend/models
        target: /app/models
      - type: bind
        source: /mnt/f/Dev/eBaySalesTool/backend/package.json
        target: /app/package.json
      # Updated to use absolute paths for WSL compatibility
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://database:27017/ebay-sales-tool # Update MongoDB URI
      - PG_HOST=database

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - REACT_APP_API_URL=http://localhost:5000

  database:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ebay_sales_tool
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
