-- Disabled legacy script: do not execute during Postgres init
-- This file is intentionally left blank to prevent auto-execution by /docker-entrypoint-initdb.d
-- Use application seeders in database/seeds/ instead.