// This file is generated by scripts/generate_swagger.js
// It should export the merged Swagger JSON for use by swagger-ui-express
const path = require('path');
let swagger;
try {
  // Try to load swagger.json from the backend directory (for Docker)
  swagger = require(path.resolve(__dirname, '../../swagger.json'));
} catch (e) {
  // Fallback to project root (for local dev)
  swagger = require(path.resolve(__dirname, '../../../swagger.json'));
}
module.exports = swagger;
